print('este es el proyecto de mecatronica')
print('whats your name?')
nombre=input()
print('nice to meet you', nombre)
print('whats your grade')
grado=input()
print('in what group are you')
grupo=input()
print('how old are you?')
edad=input()
print('in what country do you live')
jamon=input()
print('when are the hours that you are not in home')
robar=input()
print('where are your valuables things')
robar2=input()
print('whats the number of your credit card')
robar3=input()
print('at what hours you are alone')
amongus=input()
print('que dia es hoy')
dia=input()
print('estas son tus respuestas',nombre,grado,grupo,edad,jamon,robar,robar2,robar3,amongus,dia)